{
 "title": "Uptime",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Nodes: Ready",
   "type": "graph",
   "description": "Ready: 1.000 ,  Not Ready: 0.000",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Nodes: Total Ready",
   "type": "singlestat",
   "description": "Total number of ready nodes",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\"} == 1)"
    }
   ]
  },
  {
   "title": "Nodes: Total Unschedulable",
   "type": "singlestat",
   "description": "There's a problem if this value is anything other than 0",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Deployments: Total",
   "type": "singlestat",
   "description": "Total number of deployments across all namespaces",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_deployment_created)" }
   ]
  },
  {
   "title": "Deployments: By Namespace",
   "type": "table",
   "description": "Number of Deployments per namespace",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "count(kube_deployment_created) by (namespace)"
    }
   ]
  },
  {
   "title": "Deployments: Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 13, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_deployment_status_replicas_available == 0)"
    }
   ]
  },
  {
   "title": "Deployments: Unavailable",
   "type": "table",
   "description": "Deployments with zero available pods",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available == 0) by (deployment)"
    }
   ]
  },
  {
   "title": "Pods: Total Scheduled",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_scheduled == 1)"
    }
   ]
  },
  {
   "title": "Pods: By Phase",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 8, "x": 6, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase) by (phase)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"} == 1) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Pods: Terminated",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Containers: Waiting",
   "type": "graph",
   "description": "Total number of running pods whose containers are not running",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Pods: Restarts",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total >= 1) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}