{
 "title": "Blockchain Nodes",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "currency", "query": "label_values(currency)" }
  ]
 },
 "panels": [
  {
   "title": "Block Height",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Height ($currency)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "repeat": "currency",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "block_height{currency=\"$currency\"}",
       "legendFormat": "Blocks"
      }
     ]
    },
    {
     "title": "Block Height ($currency)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "block_height{currency=\"$currency\"}",
       "legendFormat": "Blocks"
      }
     ]
    },
    {
     "title": "Block Height ($currency)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "block_height{currency=\"$currency\"}",
       "legendFormat": "Blocks"
      }
     ]
    },
    {
     "title": "Block Height ($currency)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "block_height{currency=\"$currency\"}",
       "legendFormat": "Blocks"
      }
     ]
    },
    {
     "title": "Block Height ($currency)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "block_height{currency=\"$currency\"}",
       "legendFormat": "Blocks"
      }
     ]
    }
   ]
  },
  { "title": "Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Connected Peers ($currency)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "repeat": "currency",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{currency=\"$currency\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  { "title": "Fees", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Fee Price ($currency)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "repeat": "currency",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tx_fee_price{currency=\"$currency\"}",
     "legendFormat": "Tx Fee Price"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Transactions ($currency)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "repeat": "currency",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "block_transaction_count{currency=\"$currency\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Uncle Count (eth)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "block_uncle_count{currency=\"eth\"}",
     "legendFormat": "Uncles"
    }
   ]
  }
 ]
}