{
 "title": "Exchange Proxy",
 "tags": [ "Prometheus" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "exchange", "query": "label_values(exchange)" }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Exchange Proxy Health", "type": "alertlist", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 } },
  {
   "title": "Overall error count (6h)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(production_exchange_proxy_errors_count[6h]))"
    }
   ]
  },
  {
   "title": "Overall error count (24h)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(production_exchange_proxy_errors_count[24h]))"
    }
   ]
  },
  {
   "title": "Error count by exchange",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(production_exchange_proxy_errors_count{exchange=~\"$exchange\"}[30m])) by (exchange)",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  { "title": "Message Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Messages received (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(production_exchange_proxy_messages_received{exchange=\"amqp\"}[1m])",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Exchange Processing Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(production_exchange_proxy_request_message_time_sum{exchange=~\"$exchange\"}[15m])) by (exchange)/\r\n  sum(rate(production_exchange_proxy_request_message_time_count{exchange=~\"$exchange\"}[15m])) by (exchange)",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "Messages received by exchange (per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(production_exchange_proxy_messages_received{exchange=~\"$exchange\",value=\"total\"}[1m])) by (exchange))",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "Total Processing Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(production_exchange_proxy_request_proc_time_sum{key=\"full_time\", exchange=~\"$exchange\"}[15m])) by (exchange)/\r\n  sum(rate(production_exchange_proxy_request_proc_time_count{key=\"full_time\", exchange=~\"$exchange\"}[15m])) by (exchange)",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "SFOX Processing Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(production_exchange_proxy_request_proc_time_sum{key=\"full_time\", exchange=~\"$exchange\"}[15m])) by (exchange)/\r\n  sum(rate(production_exchange_proxy_request_proc_time_count{key=\"full_time\", exchange=~\"$exchange\"}[15m])) by (exchange)) - (sum(rate(production_exchange_proxy_request_message_time_sum{exchange=~\"$exchange\"}[15m])) by (exchange)/\r\n  sum(rate(production_exchange_proxy_request_message_time_count{exchange=~\"$exchange\"}[15m])) by (exchange))",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "Messages received per type by exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "($exchange) - Messages by type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
     "repeat": "exchange",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(production_exchange_proxy_messages_received{exchange=\"$exchange\",value=\"total\"}[1m])",
       "legendFormat": "{{pair}}"
      }
     ]
    },
    {
     "title": "($exchange) - Messages by type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(production_exchange_proxy_messages_received{exchange=\"$exchange\",value=\"total\"}[1m])",
       "legendFormat": "{{pair}}"
      }
     ]
    },
    {
     "title": "($exchange) - Messages by type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(production_exchange_proxy_messages_received{exchange=\"$exchange\",value=\"total\"}[1m])",
       "legendFormat": "{{pair}}"
      }
     ]
    },
    {
     "title": "($exchange) - Messages by type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(production_exchange_proxy_messages_received{exchange=\"$exchange\",value=\"total\"}[1m])",
       "legendFormat": "{{pair}}"
      }
     ]
    },
    {
     "title": "($exchange) - Messages by type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(production_exchange_proxy_messages_received{exchange=\"$exchange\",value=\"total\"}[1m])",
       "legendFormat": "{{pair}}"
      }
     ]
    },
    {
     "title": "($exchange) - Messages by type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(production_exchange_proxy_messages_received{exchange=\"$exchange\",value=\"total\"}[1m])",
       "legendFormat": "{{pair}}"
      }
     ]
    },
    {
     "title": "($exchange) - Messages by type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(production_exchange_proxy_messages_received{exchange=\"$exchange\",value=\"total\"}[1m])",
       "legendFormat": "{{pair}}"
      }
     ]
    },
    {
     "title": "($exchange) - Messages by type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(production_exchange_proxy_messages_received{exchange=\"$exchange\",value=\"total\"}[1m])",
       "legendFormat": "{{pair}}"
      }
     ]
    },
    {
     "title": "($exchange) - Messages by type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(production_exchange_proxy_messages_received{exchange=\"$exchange\",value=\"total\"}[1m])",
       "legendFormat": "{{pair}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Times by Exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "($exchange) - Request times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "repeat": "exchange",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(production_exchange_proxy_request_message_time_bucket{exchange=\"$exchange\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Message Process Times by Exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "($exchange) - Full process times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
     "repeat": "exchange",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(production_exchange_proxy_request_proc_time_bucket{exchange=\"$exchange\",key=\"full_time\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages received by pair",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(delta(production_exchange_proxy_messages_received{exchange!=\"amqp\",value!=\"total\"}[1m])) by (value))",
       "legendFormat": "{{value}}"
      }
     ]
    },
    {
     "title": "Wait times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(production_exchange_proxy_request_proc_time_bucket{key=\"wait_time\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}