{
 "title": "Go trader",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "exchange", "query": "label_values(exchange)" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Done", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total messages received (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(production_go_trader_messages_received[1m])) - sum(delta(production_go_trader_messages_received{type=\"orderbook\",key=\"total\"}[1m]))"
    }
   ]
  },
  {
   "title": "Messages received by type (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(production_go_trader_messages_received{key!=\"total\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(delta(production_go_trader_messages_received{type=\"rpc\",key=\"total\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Orderbooks received (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(production_go_trader_messages_received{type=\"orderbook\",key!=\"total\"}[1m])",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Total messages sent (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(production_go_trader_messages_sent[1m]))"
    }
   ]
  },
  {
   "title": "Total messages sent by location (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(production_go_trader_messages_sent[1m])) by (location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Total RPC messages sent by exchange (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(production_go_trader_messages_sent{location=\"rpc\",exchange=~\"$exchange\"}[1m])) by (exchange)",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "(0 Algo) Order status calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 1, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(production_go_trader_orders_status{algorithm=\"0\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "(200 Algo) Order status calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(production_go_trader_orders_status{algorithm=\"200\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Error count by exchange",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(production_go_trader_errors_count{type!=\"get_data\"}[15m])) by (type)",
     "legendFormat": "{{type}} - {{problem}} - {{extra}}"
    }
   ]
  },
  {
   "title": "By pair",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(production_go_trader_orders_status[1m])) by (pair)",
     "legendFormat": "{{pair}}"
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Overall error count (WIP)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 44 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(delta(production_exchange_proxy_errors_count[$interval]))"
    }
   ]
  },
  {
   "title": "Average request time by exchange",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(production_exchange_proxy_request_message_time_sum{exchange=~\"$exchange\"}[15m])) by (exchange)/\r\n  sum(rate(production_exchange_proxy_request_message_time_count{exchange=~\"$exchange\"}[15m])) by (exchange)",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "Messages received by exchange (per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(production_exchange_proxy_messages_received{exchange=~\"$exchange\",value=\"total\"}[1m])) by (exchange))",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "Average message process time by exchange",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(production_exchange_proxy_request_proc_time_sum{key=\"full_time\", exchange=~\"$exchange\"}[15m])) by (exchange)/\r\n  sum(rate(production_exchange_proxy_request_proc_time_count{key=\"full_time\", exchange=~\"$exchange\"}[15m])) by (exchange)",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "Average message proc time (minus average request time) by exchange",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(production_exchange_proxy_request_proc_time_sum{key=\"full_time\", exchange=~\"$exchange\"}[15m])) by (exchange)/\r\n  sum(rate(production_exchange_proxy_request_proc_time_count{key=\"full_time\", exchange=~\"$exchange\"}[15m])) by (exchange)) - (sum(rate(production_exchange_proxy_request_message_time_sum{exchange=~\"$exchange\"}[15m])) by (exchange)/\r\n  sum(rate(production_exchange_proxy_request_message_time_count{exchange=~\"$exchange\"}[15m])) by (exchange))",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "RPC messages sent per type by exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 }
  },
  {
   "title": "($exchange) - RPC messages sent by type (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "repeat": "exchange",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(production_go_trader_messages_sent{location=\"rpc\", exchange=\"$exchange\"}[1m])",
     "legendFormat": "{{info}}"
    }
   ]
  },
  {
   "title": "Request Times by Exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "($exchange) - Request times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "repeat": "exchange",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(production_exchange_proxy_request_message_time_bucket{exchange=\"$exchange\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Message Process Times by Exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "($exchange) - Full process times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 64 },
     "repeat": "exchange",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(production_exchange_proxy_request_proc_time_bucket{exchange=\"$exchange\",key=\"full_time\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "($exchange) - Full process times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(production_exchange_proxy_request_proc_time_bucket{exchange=\"$exchange\",key=\"full_time\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "($exchange) - Full process times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(production_exchange_proxy_request_proc_time_bucket{exchange=\"$exchange\",key=\"full_time\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "($exchange) - Full process times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(production_exchange_proxy_request_proc_time_bucket{exchange=\"$exchange\",key=\"full_time\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "($exchange) - Full process times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(production_exchange_proxy_request_proc_time_bucket{exchange=\"$exchange\",key=\"full_time\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "($exchange) - Full process times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(production_exchange_proxy_request_proc_time_bucket{exchange=\"$exchange\",key=\"full_time\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "($exchange) - Full process times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(production_exchange_proxy_request_proc_time_bucket{exchange=\"$exchange\",key=\"full_time\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "($exchange) - Full process times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(production_exchange_proxy_request_proc_time_bucket{exchange=\"$exchange\",key=\"full_time\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "($exchange) - Full process times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(production_exchange_proxy_request_proc_time_bucket{exchange=\"$exchange\",key=\"full_time\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages received by pair",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(delta(production_exchange_proxy_messages_received{exchange!=\"amqp\",value!=\"total\"}[1m])) by (value))",
       "legendFormat": "{{value}}"
      }
     ]
    },
    {
     "title": "Wait times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(production_exchange_proxy_request_proc_time_bucket{key=\"wait_time\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}