{
 "title": "Orbit",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Buffer Length Per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(production_orbit_message_buffer_length_count[1m])/rate(production_orbit_message_buffer_length_sum[1m])",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Messages Transferred Per Min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(production_orbit_messages_total[1m])",
     "legendFormat": "{{type}} - {{worker}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "production_orbit_connections_count{}",
     "legendFormat": "{{router}}"
    }
   ]
  },
  {
   "title": "Requests Per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(production_orbit_request_count[1m])",
     "legendFormat": "{{router}}"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "production_orbit_subscription_count{}",
     "legendFormat": "{{feed}}"
    }
   ]
  },
  {
   "title": "Goroutines Per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(go_goroutines{job=\"Orbit\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}